### PR TITLE
feat: dependencies bump and ignore packages

### PR DESCRIPTION
**Pull request by davikawasaki**
Brings [@qiwi/multi-semantic-release](https://github.com/qiwi/multi-semantic-release) fork PRs on bumping dependencies and ignore packages:

- fix: avoid non-updated local dependencies bump: https://github.com/qiwi/multi-semantic-release/pull/33
- fix: local dependencies correct bump from release to prerelease: https://github.com/qiwi/multi-semantic-release/pull/34
- chore: refactor nextPreVersion to reduce cognitive complexity: https://github.com/qiwi/multi-semantic-release/pull/35
- feat: ignore packages to be released with workspaces and CLI: https://github.com/qiwi/multi-semantic-release/pull/42
- fix: release process crash due to incorrect package version name: https://github.com/qiwi/multi-semantic-release/pull/45

### CODE REVIEW

**Review by antongolub — APPROVED** [review]

**Comment by antongolub** [comment]
@davikawasaki,

Stellar work. Thanks a lot for this improvement.

**Comment by antongolub** [comment]
@dhoulb,

https://travis-ci.com/github/dhoulb/multi-semantic-release/jobs/488832498
GH_TOKEN has become invalid. I had to replace it with my own.

**Comment by betaboon** [comment]
@davikawasaki is there any way to configure to-be-ignored packages with a config-file ?

**Comment by antongolub** [comment]
Maybe it's time to introduce `.msrrc{js,json,yml}` files and `msr` config field for package.json?

**Comment by davikawasaki** [comment]
@antongolub we could do that, but are we still going to maintain the ignore packages feature on `workspaces`? What if the user sets it on the `.msrrc`, `workspaces` and also CLI? Should we stack things up? Just thinking if it makes sense to provide this feature is so many different places.

**Comment by antongolub** [comment]
CLI args usually take precedence. So we can just merge them on top of 'config'.

**Comment by betaboon** [comment]
my usecase is this:
i have several packages in a monorepo that i want to neither be published (for which `private: true` would be enough) nor release/version-tagged(for which the cli option would work).
but relying on commandline options seems to error-prone to me.
and i cant add `!` in the workspace-configuration as it would be ignored by the package-manager itself.

i would be in favor of using a `.msrrc` (or even better full `cosmicconfig`-support).
maybe it would even be favorable to "highjack" `release.config.js`(and its sisters) to not introduce yet another config-file

**Pull request merged**
