### PR TITLE
feat: run publish step in parallel

### PR DESCRIPTION
**Pull request by antongolub**
Long awaited feature with a breaking change.

```
error semantic-release@17.0.7: The engine "node" is incompatible with this module. Expected version ">=10.18". Got "8.17.0"
```

### CODE REVIEW

**Comment by antongolub** [comment]
@dhoulb Ah. I found an issue. Do not merge.

**Comment by antongolub** [comment]
Fixed a minor bug with a partial release.

Before: [builds/167725647](https://travis-ci.com/github/antongolub/release-testing/builds/167725647)
After: [builds/167730806](https://travis-ci.com/github/antongolub/release-testing/builds/167730806)

**Comment by antongolub** [comment]
@dhoulb, could you take a look? Have I missed something important?

**Comment by dhoulb** [comment]
@antongolub Appreciate the upstream PR — I don't have time to review deeply so I'm going to merge this and cross my fingers for good luck! 

My current preferred solutions for the "monorepos and semantic release" problem are:

1. Don't bother with monorepos — deploy a single package to NPM and reference deeply with e.g. `import x from "mypackage/subpackage";`
2. Write a complete replacement for semantic release that's designed to support monorepos natively without the technical debt and issues we've had to work around here.

**Pull request merged**
