### PR TITLE
chore: move jest to devDependencies

### PR DESCRIPTION
**Pull request by dankins**
Jest is currently in dependencies, and was causing issues having multiple versions of Jest with create-react-app

### CODE REVIEW

**Comment by dhoulb** [comment]
Thanks @dankins makes sense to me.

**Comment by dankins** [comment]
:pray: thanks! Could you please publish a new version to NPM at your convenience?

**Comment by dhoulb** [comment]
@dankins Releases are automatic and semantic — because this commit is "chore" and not "fix" it won't trigger a release (I missed that too!) I'll change something random to trigger a "fix" release.

**Pull request merged**
