### PR TITLE
feat: support workspace.packages notation

### LINKED ISSUE #21: Can't find packages when `nohoist` is configured
Hey folks! We're running into a little issue:

We've configured [`nohoist`](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/) to deal with some Typescript malarkey. In our root package.json, workspaces looks like this:

```json
  "workspaces": {
    "packages": [
      "packages/core",
      "packages/react"
    ],
    "nohoist": [
      "**/react-native",
      "**/react-native/**"
    ]
  },
```

This leads to this error:

```bash
[multi-semantic-release]: TypeError: package.json: workspaces: Must be non-empty array of string
```

Should this be supported? We can work around this for now by feeding it the path of projects manually by using the programmatic API, but if you think it's something that _should_ work I'd gladly submit a fix.

Thanks ❤️

### PR DESCRIPTION
**Pull request by StevenLangbroek**
Closes #21

### CODE REVIEW

**Comment by antongolub** [comment]
Hi, @StevenLangbroek

Looks reasonable.

Could you rewrite workspace resolver a little shorter?
https://github.com/24i/multi-semantic-release/commit/1d0eb456d6473f0e04e4858de9416bd2b8e229b9

**Comment by StevenLangbroek** [comment]
@antongolub done :)

**Comment by antongolub** [comment]
@CHaNGeTe

FYI, your proposal is now a part of **msr**.

**Pull request merged**
