### PR TITLE
feat(prerelease): added logic to bump local dependencies on prereleases

### PR DESCRIPTION
**Pull request by davikawasaki**
PR that reflects changes already applied to [@qiwi/multi-semantic-release](https://github.com/qiwi/multi-semantic-release). 
Covers the following bugs presented there:

- https://github.com/qiwi/multi-semantic-release/issues/25
- https://github.com/qiwi/multi-semantic-release/issues/31

### CODE REVIEW

**Review by antongolub — APPROVED** [review]

**Comment by antongolub** [comment]
@davikawasaki,

Thanks!

**Comment by antongolub** [comment]
@davikawasaki,

Let's remove `package-lock.json`. We have `yarn.lock` already.

**Comment by davikawasaki** [comment]
@antongolub done. Sorry, didn't see that the repo was using `yarn`.

**Pull request merged**
